<div class="footer-wrapper">
  <div class="store-column">
    <div class="header">STORE</div>
    <div><a href="http://chargepoint.com/products/sales">Contact Sales</a></div>
  </div>
  <div class="support-column">
    <div class="header">SUPPORT</div>
    <div><a href="http://chargepoint.com/support/owner-faq">Hardware Support</a></div>
    <div><a href="http://chargepoint.com/support/driver-faq">24/7 Driver Support</a></div>
    <div><a href="http://chargepoint.com/support/guides/">Data Sheet & Install Guides</a></div>
  </div>
  <div class="email-column">
    <label for="email-address">Plug into the latest EV news and incentives.</label>
    <span class="inputWithButton">
      <input type="text" placeholder="Email Address" name="email-address"><button class="pale">Submit</button>
    </span>
  </div>
</div>
