<div class="wrap"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/cp-overview-1-main-banner-1.png" width="1280" height="380" />
    <div class="arrow"></div>
    <h1 class="message">Charge Faster, Go Farther</h1><a href="/chargepoint-home"><button class="primary-button big">Get Your Home Charger</button></a></div>
<h3 class="power-title">Power Up 6X Faster</h3>
<div class="power-box">
    <div class="power-animation">
        <div class="product-description">
            <div class="top">Wall outlet</div>
            <div class="bottom">ChargePoint Home</div>
        </div>
        <div class="home">
            <div class="top"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/power/Faster_Graphic_Home_icon.png" /></div>
            <div class="bottom"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/power/Faster_Graphic_Home_icon.png" /></div>
        </div>
        <div class="journey">
            <div class="top"><input type="range"></div>
            <div class="bottom"><input type="range"></div>
        </div>
        <div class="destination"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/power/Faster_Graphic_City_Building_icon.png" width="114" height="147" /></div>
        <div class="description">
            <div class="top"><span class="value">0</span>mi added</div>
            <div class="bottom"><span class="value">0</span>mi added</div>
        </div>
    </div>
    <div class="power-handle">
        <div><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/power/Faster_Graphic_Grab.png" /></div><input type="range"></div>
    <div class="power-footer-message">A wall outlet just doesn’t cut it. See how much faster ChargePoint® Home can charge your EV.</div>
</div>
<article class="blue large-bottom-margin">
    <h3 class="charging-message1">Manage Charging from Anywhere</h3>
    <div class="charging-message1 round">Set reminders, schedule charging and track energy use with the ChargePoint app.</div>
    <div class="content-right scroll"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/cp-webstore-js-3-connected.png" width="740" height="350" /></div>
</article>
<article class="med-small-bottom-margin">
    <div class="content-left"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/cp-webstore-js-4-network.png" width="740" height="350" /></div>
    <h3 class="charging-message2">All Your Charging In One Place</h3>
    <div class="charging-message2 round">See how much you’re charging and saving all in one account.</div>
</article>
<article class="blue lg-med-bottom-margin">
    <h3 class="charging-message3">Charges All EVs</h3>
    <div class="charging-message3 round">Home can charge any EV, including your next one.</div>
    <div class="badges"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/cp-overview-5-all-ev-auto-badges-rev.png" width="265" height="64" /></div>
    <div class="content-right scroll"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/cp-overview-5-all-ev-connector-1.png" width="740" height="350" /></div>
</article>
<div class="get-home">
    <div class="message">Ready to speed up?</div><a href="/chargepoint-home"><button class="primary-button big">Get Home</button></a></div>
<article class="small-med-bottom-margin">
    <div class="content-left"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/easy-install.png" width="740" height="350" /></div>
    <h3 class="charging-message4">Installation Is a Breeze</h3>
    <div class="charging-message4 round">Home is easy to install indoors or out. We have a network of trusted installers near you.</div>
</article>
<article class="blue small-bottom-margin">
    <h3 class="charging-message5">Tested by the Best</h3>
    <div class="charging-message5 round">The first charger tested and proven to be both efficient and safe.</div>
    <div class="content-right scroll"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/cp-webstore-js-7-energystar.png" width="740" height="350" /></div>
</article>
<article class="extra-lg-bottom-margin">
    <div class="content-left"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/homestore-smaller-than.png" width="740" height="350" /></div>
    <h3 class="charging-message6">Fits in Your Garage</h3>
    <div class="charging-message6 round">Home fits in your garage and with your lifestyle.</div>
</article>
<div class="not-our-word medium-bottom-margin">
    <div class="message">Don’t Take Our Word for It</div>
    <div class="quote-icon"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/icon-quote.png" width="98" height="82px" /></div>
    <div class="quote-box round">
        <div class="quote"> Looked long and hard for the best home charger... This was by far the best looking with the most features for the best value. Easy to wire and install. Exceptionally well thought out design and size.</div>
        <div class="speaker"> – MJ from Portland, OR, on Amazon</div>
    </div>
</div>
<div class="medals"><img src="/pub/static/frontend/chargePoint/cpstore/en_US/images/overview/cp-overview-9-thirdparty-validation-1.png" width="1280" height="325" /></div>
<div class="blue get-started">
  <div class="message">Get your ChargePoint Home charger today</div>
  <a href="/chargepoint-home"><button class="primary-button">Get Started</button></a>
</div>
